[tools]
act = "latest"
"aqua:caddyserver/caddy" = "latest"
bun = "latest"
go = "latest"
jless = "latest"
jnv = "latest"
lazydocker = "latest"
node = "24"
"npm:@biomejs/biome" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@moonrepo/cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:degit" = "latest"
"npm:firecrawl-mcp" = "latest"
"npm:neovim" = "latest"
"npm:opencode-ai" = "latest"
"npm:turbo" = "latest"
pnpm = "latest"
poetry = "latest"
python = "latest"
task = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
