general.import = ["~/.config/alacritty/themes/themes/ayu_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font Mono"

[window]
dimensions = { columns = 160, lines = 40 }
padding.x = 5
padding.y = 5

decorations = "buttonless"
# Set to None to let macOS handle Option key for compose/input methods
option_as_alt = "None"

opacity = 0.92

blur = false

[mouse]
hide_when_typing = false

[terminal]

# [keyboard]
# bindings = [
#   { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
#   { key = "Tab", mods = "Shift|Control", chars = "\u001b[27;6;9~" },
# ]
